export const OPERATIONS = {
    UP:'up',
    COPY: "cp",
    CAT: "cat",
    MOVE: "mv",
    RENAME: "rn",
    REMOVE: "rm",
    MKDIR: "mkdir",
    CD: "cd",
    LS: "ls",
    CAT: "cat",
    ADD: "add",
    HASH: "hash",
    COMPRESS: "compress",
    DECOMPRESS: "decompress",
    OS:"os",
    FILE_MANAGER:"fm",
    SIGINT: "SIGINT",
    EXIT:".exit",
    CLEAR:"clear",
}